{
	"version": 1732323420,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/soal-sheet0.png",
		"images/jawabana-sheet0.png",
		"images/next-sheet0.png",
		"images/back-sheet0.png",
		"images/backgrounddefeat-sheet0.png",
		"images/logogameselesai-sheet0.png",
		"images/kotokdefeat-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btntry-sheet0.png",
		"images/play_baru__1___1_removebgpreview-sheet0.png",
		"images/game___1_removebgpreview-sheet0.png",
		"images/game-sheet0.png",
		"images/game2-sheet0.png",
		"images/sprite-sheet0.png",
		"media/wav salah effect.m4a",
		"media/wav salah effect.ogg",
		"media/sound effects benar wav.m4a",
		"media/sound effects benar wav.ogg",
		"media/opening wav.m4a",
		"media/opening wav.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"rahasia.txt"
	]
}